from __future__ import annotations

import json
import sys
import traceback
from pathlib import Path
from typing import Any


class FreeCADWorker:
    def __init__(self):
        import FreeCAD as App

        self.App = App
        self.Gui = self._load_gui()
        self.doc = None
        self.document_name = "Text23DGeneratedModel"
        self.namespace: dict[str, Any] = {}
        self.create_document(self.document_name)

    def _load_gui(self):
        try:
            import FreeCADGui as Gui
        except Exception:
            return None
        return Gui

    def create_document(self, name: str | None = None) -> dict[str, Any]:
        self.close_document()
        self.document_name = _safe_document_name(name or "Text23DGeneratedModel")
        self.doc = self.App.newDocument(self.document_name)
        self.App.setActiveDocument(self.doc.Name)
        if self.Gui is not None:
            try:
                self.Gui.ActiveDocument = self.Gui.getDocument(self.doc.Name)
            except Exception:
                pass
        self.namespace = self._execution_namespace()
        return {
            "document": self.doc.Name,
            "message": "Created a fresh live FreeCAD document.",
        }

    def close_document(self) -> None:
        if self.doc is None:
            return
        try:
            self.App.closeDocument(self.doc.Name)
        except Exception:
            pass
        self.doc = None

    def execute_code(self, code: str) -> dict[str, Any]:
        if self.doc is None:
            self.create_document(self.document_name)
        exec(code, self.namespace, self.namespace)
        self.doc.recompute()
        return {
            "message": "Code executed in the live FreeCAD document.",
            "object_count": len(self.doc.Objects),
            "objects": self.objects(),
        }

    def objects(self) -> list[dict[str, Any]]:
        if self.doc is None:
            return []
        return [_object_manifest(obj) for obj in self.doc.Objects]

    def get_object(self, name: str) -> dict[str, Any]:
        target = name.strip().lower()
        for obj in self.objects():
            names = {
                str(obj.get("name", "")).lower(),
                str(obj.get("label", "")).lower(),
            }
            if target in names:
                return {"object": obj}
        raise RuntimeError(f"Object not found: {name}")

    def get_view(self, output_path: str) -> dict[str, Any]:
        if self.Gui is None:
            raise RuntimeError("FreeCADGui is not available; cannot capture viewport.")
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        self._activate_view()
        view = self.Gui.ActiveDocument.ActiveView
        try:
            view.viewAxonometric()
            view.fitAll()
        except Exception:
            pass
        view.saveImage(str(path), 1280, 720, "White")
        if not path.exists() or path.stat().st_size == 0:
            raise RuntimeError("FreeCAD viewport screenshot was not written.")
        return {
            "message": "Captured FreeCAD viewport screenshot.",
            "image_path": str(path),
            "objects": self.objects(),
        }

    def export_preview_mesh(self, output_path: str) -> dict[str, Any]:
        import Mesh

        if self.doc is None:
            raise RuntimeError("No FreeCAD document is active.")
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        self.doc.recompute()
        objects = self._exportable_objects()
        if not objects:
            raise RuntimeError("No exportable FreeCAD objects were produced.")
        Mesh.export(objects, str(path))
        if not path.exists() or path.stat().st_size == 0:
            raise RuntimeError("FreeCAD preview mesh was not written.")
        return {
            "message": "Exported temporary FreeCAD preview mesh.",
            "mesh_path": str(path),
            "objects": self.objects(),
        }

    def export_model(self, output_dir: str) -> dict[str, Any]:
        import Mesh
        import Part

        if self.doc is None:
            raise RuntimeError("No FreeCAD document is active.")
        output = Path(output_dir)
        output.mkdir(parents=True, exist_ok=True)
        self.doc.recompute()
        objects = self._exportable_objects()
        if not objects:
            raise RuntimeError("No exportable FreeCAD objects were produced.")

        native_path = output / "model.FCStd"
        step_path = output / "model.step"
        stl_path = output / "preview.stl"
        objects_path = output / "objects.json"
        script_path = output / "live_session.py"

        self.doc.saveAs(str(native_path))
        Part.export(objects, str(step_path))
        Mesh.export(objects, str(stl_path))
        objects_path.write_text(json.dumps(self.objects(), indent=2), encoding="utf-8")
        script_path.write_text(
            "# Generated by Text23D live FreeCAD worker.\n"
            "# Open model.FCStd for the editable feature tree.\n",
            encoding="utf-8",
        )
        return {
            "message": "Final FreeCAD artifacts are ready.",
            "objects": self.objects(),
            "artifacts": {
                "native": str(native_path),
                "step": str(step_path),
                "stl": str(stl_path),
                "glb": None,
                "script": str(script_path),
                "runner_log": None,
            },
            "script_path": str(script_path),
        }

    def _exportable_objects(self) -> list[Any]:
        if self.doc is None:
            return []
        return [
            obj
            for obj in self.doc.Objects
            if hasattr(obj, "Shape") and not getattr(obj.Shape, "isNull", lambda: True)()
        ]

    def _activate_view(self) -> None:
        if self.Gui is None or self.doc is None:
            return
        try:
            self.Gui.showMainWindow()
        except Exception:
            pass
        try:
            self.Gui.ActiveDocument = self.Gui.getDocument(self.doc.Name)
        except Exception:
            pass
        try:
            self.Gui.SendMsgToActiveView("ViewFit")
        except Exception:
            pass

    def _execution_namespace(self) -> dict[str, Any]:
        import Mesh
        import Part

        namespace = {
            "__builtins__": __builtins__,
            "App": self.App,
            "FreeCAD": self.App,
            "Part": Part,
            "Mesh": Mesh,
            "doc": self.doc,
        }
        if self.Gui is not None:
            namespace["Gui"] = self.Gui
            namespace["FreeCADGui"] = self.Gui
        return namespace


def main() -> int:
    worker = FreeCADWorker()
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        request: dict[str, Any] = {}
        try:
            request = json.loads(line)
            response = handle_request(worker, request)
        except Exception as exc:
            response = {
                "id": request.get("id"),
                "ok": False,
                "content": {
                    "error": str(exc),
                    "traceback": traceback.format_exc(),
                },
            }
        sys.stdout.write(json.dumps(response) + "\n")
        sys.stdout.flush()
        if response.get("command") == "shutdown":
            break
    worker.close_document()
    return 0


def handle_request(worker: FreeCADWorker, request: dict[str, Any]) -> dict[str, Any]:
    command = request.get("command")
    args = request.get("args") or {}
    content: dict[str, Any]
    asset_path = None

    if command == "create_document":
        content = worker.create_document(args.get("name"))
    elif command == "execute_code":
        content = worker.execute_code(str(args.get("code", "")))
    elif command == "get_objects":
        objects = worker.objects()
        content = {"object_count": len(objects), "objects": objects}
    elif command == "get_object":
        content = worker.get_object(str(args.get("name", "")))
    elif command == "get_view":
        asset_path = str(args["output_path"])
        content = worker.get_view(asset_path)
    elif command == "export_preview_mesh":
        content = worker.export_preview_mesh(str(args["output_path"]))
    elif command == "export_model":
        content = worker.export_model(str(args["output_dir"]))
    elif command == "shutdown":
        content = {"message": "Worker shutting down."}
    else:
        raise RuntimeError(f"Unsupported command: {command}")

    return {
        "id": request.get("id"),
        "command": command,
        "ok": True,
        "content": content,
        "asset_path": asset_path,
    }


def _object_manifest(obj: Any) -> dict[str, Any]:
    row = {
        "name": getattr(obj, "Name", ""),
        "label": getattr(obj, "Label", ""),
        "type": getattr(obj, "TypeId", ""),
        "visible": getattr(getattr(obj, "ViewObject", None), "Visibility", None),
    }
    shape = getattr(obj, "Shape", None)
    bound_box = getattr(shape, "BoundBox", None)
    if bound_box is not None:
        row["bounds"] = {
            "x_min": getattr(bound_box, "XMin", None),
            "x_max": getattr(bound_box, "XMax", None),
            "y_min": getattr(bound_box, "YMin", None),
            "y_max": getattr(bound_box, "YMax", None),
            "z_min": getattr(bound_box, "ZMin", None),
            "z_max": getattr(bound_box, "ZMax", None),
        }
    return row


def _safe_document_name(value: str) -> str:
    cleaned = "".join(ch for ch in value if ch.isalnum() or ch in {"_", "-"}).strip()
    return cleaned[:64] or "Text23DGeneratedModel"


if __name__ == "__main__":
    raise SystemExit(main())
